[msbuild]
project = "Panels.sln"

[msbuild.properties]
PublishTrimmed = false

[github]
user = "samdouble"
repo = "panels"
branches = ["master"]

[brew]
publish = false

[nuget]
publish = false

[scoop]
publish = false
