[msbuild]
project = "Panels.sln"

[github]
user = "samdouble"
repo = "panels"
branches = ["master"]

[[pack]]
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["deb", "tar"]
publish = false

[[pack]]
rid = ["rhel-x64"]
kinds = ["rpm", "tar"]
publish = false

[[pack]]
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]
publish = false

[brew]
publish = false

[nuget]
publish = false

[scoop]
publish = false
