[msbuild]
project = "Panels.sln"

[github]
user = "samdouble"
repo = "panels"
branches = ["master"]

[[pack]]
rid = ["win-x64", "win-arm", "win-arm64"]
kinds = ["zip"]
publish = false

[brew]
publish = false

[nuget]
publish = false

[scoop]
publish = false
