<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Description>panels</Description> 
    <Copyright>samdouble</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Authors>samdouble</Authors>
    <PackageTags>releaser;packaging;deb;rpm;tool</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/samdouble/panels</PackageProjectUrl>
    <PackageLicenseExpression>BSD-2-Clause</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <CustomResourceTypesSupport>true</CustomResourceTypesSupport>
    <Version>2.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <AppDesigner Include="Properties\" />
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.7.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/schema.xsd" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
