name: Checks
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'
      - name: Audit
        run: |
          dotnet restore
          dotnet list package --vulnerable --include-transitive | tee vulnerable.out
        # test `grep -cm 1 'has the following vulnerable packages' vulnerable.out` = 0
      - name: Test
        run: |
          dotnet test
      - name: Build
        run: |
          dotnet Build

  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: master
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update version in CSProj
        env:
          VERSION: ${{ steps.release.outputs['version'] }}
        run: |
          sed -i -e 's/<Version>.*<\/Version>/<Version>${VERSION}<\/Version>/g' Panels/Panels.csproj
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: release-please--branches--master
          commit_message: "chore(master): update version in CSProj"
          commit_options: '--no-verify --signoff'
          skip_dirty_check: true