name: Deploy

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          dotnet tool install --global dotnet-releaser --version 0.17.0
          dotnet-releaser build dotnet-releaser.toml
          dotnet-releaser publish --force --github-token $GITHUB_TOKEN dotnet-releaser.toml
