name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: master
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update version in CSProj
        env:
          VERSION: ${{ steps.release.outputs['version'] }}
        run: |
          sed -i -e 's/<Version>.*<\/Version>/<Version>${VERSION}<\/Version>/g' Panels/Panels.csproj
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: release-please--branches--master
          commit_message: "chore(master): update version in CSProj"
          commit_options: '--no-verify --signoff'
          skip_dirty_check: true
