name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: master

      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          dotnet tool install --global dotnet-releaser --version 0.9.0
          dotnet-releaser build dotnet-releaser.toml
          dotnet-releaser publish --force --github-token $GITHUB_TOKEN dotnet-releaser.toml
