<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="comic">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="newpage" minOccurs="0" maxOccurs="unbounded" />
          <xs:element name="slot" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="panel" minOccurs="0" maxOccurs="2">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="text" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:attribute name="text" type="xs:string" use="required" />
                          <xs:attribute name="character" type="xs:string" use="optional" />
                          <xs:attribute name="fontSize" type="xs:string" use="optional" />
                          <xs:attribute name="left" type="xs:string" use="optional" />
                          <xs:attribute name="top" type="xs:string" use="optional" />
                          <xs:attribute name="width" type="xs:string" use="optional" />
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="description" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:attribute name="text" type="xs:string" use="required" />
                          <xs:attribute name="fontSize" type="xs:string" use="optional" />
                          <xs:attribute name="left" type="xs:string" use="optional" />
                          <xs:attribute name="top" type="xs:string" use="optional" />
                          <xs:attribute name="visible" type="xs:string" use="optional" />
                          <xs:attribute name="width" type="xs:string" use="optional" />
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                    <xs:attribute name="image" type="xs:string" use="required" />
                    <xs:attribute name="borders" type="xs:string" use="optional" />
                    <xs:attribute name="bordersColor" type="xs:string" use="optional" />
                    <xs:attribute name="bordersWidth" type="xs:decimal" use="optional" />
                    <xs:attribute name="paddingBottom" type="xs:string" use="optional" default="0" />
                    <xs:attribute name="paddingTop" type="xs:string" use="optional" default="0" />
                    <xs:attribute name="fontSize" type="xs:string" use="optional" />
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <xs:attribute name="fontSize" type="xs:string" use="optional" />
              <xs:attribute name="maxPaddingLeft" type="xs:string" use="optional" default="0" />
              <xs:attribute name="maxPaddingRight" type="xs:string" use="optional" default="0" />
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" use="required"/>
      <xs:attribute name="bordersColor" type="xs:string" use="optional" />
      <xs:attribute name="bordersWidth" type="xs:decimal" use="optional" />
      <xs:attribute name="fontSize" type="xs:string" use="optional" default="12"/>
      <xs:attribute name="marginBottom" type="xs:string" use="optional" />
      <xs:attribute name="marginLeft" type="xs:string" use="optional" />
      <xs:attribute name="marginRight" type="xs:string" use="optional" />
      <xs:attribute name="marginTop" type="xs:string" use="optional" />
      <xs:attribute name="rowsPerPage" type="xs:string" use="optional" default="3" />
      <xs:attribute name="showPageNumbers" type="xs:boolean" use="optional" default="true" />
      <xs:attribute name="horizontalPanelSpacing" type="xs:string" use="optional" />
      <xs:attribute name="verticalPanelSpacing" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

</xs:schema>
